name: Movie Scraper Bot
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install requests beautifulsoup4
      - name: Run Scraper
        run: python scraper.py
      - name: Commit Changes
        run: |
          git config --global user.name "LEX-BOT"
          git config --global user.email "bot@lex.com"
          git add index.html
          git commit -m "Auto Update Movies" || echo "No changes"
          git push
