name: Movie Scraper Bot
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:  # هذا هو السطر السحري الذي سيحل مشكلة الـ 403 نهائياً
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # تحديث للإصدار v3 أضمن
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install requests beautifulsoup4
      - name: Run Scraper
        run: python scraper.py
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto Update Movies" || echo "No changes to commit"
          git push
